LEVEL = ../..
include ../Makefile.common
ACCELS="dotproduct,dotproduct_pSlice"

clean:
	rm -r -f tmp.bc *.rpt *.dot *.l.bc *.v *.qsf *.tex *.sdc *.txt *.mif *.orig_c.v *.stitchedup_c.v *.keep *runVsim *_tb.v *.wrapper.v transcript *.ll *.bc *.ver *.csvi _d3graph/ *.csv
	rm -f -r work AXIWrapper
	rm -f *.log *.jou
	rm -f _packageIPScript.tcl
	rm -f runVsim_*
	rm -rf output
	rm -f *_hw.tcl
	rm -f parallelaccels.tcl
	rm -f *.do
	rm -f legup_sopc.tcl
	rm -f *.elf
	rm -f *.o
	rm -f *.s
	rm -f *.src
	rm -f *.srec
